version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    command: npm start
    restart: always
    networks:
      - internal

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:8000 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker app:app
    restart: always
    networks:
      - internal

  caddy:
    image: caddy:2-alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - front-end
      - back-end
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  caddy_data:
